# Ultralytics YOLO 🚀, AGPL-3.0 license
# Publish pip package to PyPI https://pypi.org/project/ultralytics/

name: Publish to PyPI and SyPI

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUILDMASTER_PAT }} 
          fetch-depth: 0
      - name: Set up Python environment
        uses: actions/setup-python@v5
        id: cp311
        with:
          python-version: "3.11"
          update-environment: false
      - name: Install dependencies
        run: |
          ${{ steps.cp311.outputs.python-path }} -m pip install --upgrade pip wheel build twine
          ${{ steps.cp311.outputs.python-path }} -m pip install -e ".[dev]" openai --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Publish to PyPI
        continue-on-error: true
        run: |
          ${{ steps.cp311.outputs.python-path }} -m build
          ${{ steps.cp311.outputs.python-path }} -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      - name: Publish to SyPI
        continue-on-error: true
        run: |
          ${{ steps.cp311.outputs.python-path }} -m build
          ${{ steps.cp311.outputs.python-path }} -m twine upload dist/* --repository-url https://jenkins:3000/api/packages/SYNENTEC/pypi -u BuildMaster -p ${{ secrets.BUILDMASTER_PAT }} --cert "\\SYNENTEC-SV01\works$\004 -- Software Development\Tools\Build\Gitea.pem"
